apiVersion: v1
kind: Pod
metadata:
  labels:
    name: mysql-sipm
  name: mysql-sipm
  namespace: siplay
spec:
  containers:
    - name: master
      image: mysql
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: sipm
