apiVersion: v1
kind: Pod
metadata:
  labels:
    name: rabbitmq-sipm
  name: rabbitmq-sipm
  namespace: siplay
spec:
  containers:
    - name: rabbitmq
      image: rabbitmq:3-management
      ports:
        - containerPort: 15672
      env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
