apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis-sipm
  name: redis-sipm
  namespace: siplay
spec:
  containers:
    - name: master
      image: redis
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "0.1"
